# Gradle JVM settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (1.21.11 unobfuscated)
minecraft_version=1.21.11
loom_version=1.14.0-alpha.31
loader_version=0.18.1
fabric_version=0.139.4+1.21.11

# Mod Properties
mod_version=1.0.0-alpha.1
maven_group=com.millenaire
archives_base_name=millenaire-reborn
mod_id=millenaire
